Test multiple froups
cliqz-oss/robotstxt pull request #1
Opened 2017-01-12 15:41 UTC by artem-cliqz

2017-01-12 15:45 UTC, artem-cliqz commented
I also have a different version that merges groups per user-agent together. It is same amount of code, but looks a bit messier.
I made an assumption here that if any group disallows, we disallow.

2017-01-16 09:35 UTC, dbalan requested changes
Its better to add comments (replace the ones we deleted) explaining the current situation

2017-01-16 10:23 UTC, artem-cliqz commented
Done, could you have a look?

2017-01-16 10:40 UTC, dbalan approved these changes

2017-01-16 10:42 UTC, merged